### ISSUE TITLE
Question on usage in AMST2

### ISSUE THREAD

**Issue by tatianawoller** [jhennies/AMST2#1]
Hi,

My colleague (@bpavie) and I would like to test your AMST2 pipeline to  align some FIB-SEM datasets.
However, we have a few questions for you.

1. In [your example](https://github.com/jhennies/AMST2/blob/main/examples/pre_alignment.sh), what is the meaning of z parameter of template_roi ?
2. In [your example](https://github.com/jhennies/AMST2/blob/main/examples/pre_alignment.sh), what are the units of the parameters of template_roi ?
3. Would you be open to share an example dataset to see how your AMST2 pipeline works?

Thank you in advance and best,

Benjamin and Tatiana

**Comment by jhennies** [comment]
Hi Tatiana, hi Benjamin,

Thanks for your interest in this. 
I haven't used the function in the example for quite a while, it might be that it's a bit out-dated. 

Let's do the following:
- I'll have a look at it and give you a more up-to-date example.
- I'll also look for a test dataset and share it with you.

Cheers,
Julian

**Comment by tatianawoller** [comment]
Hi Julian,

Thank you for sharing an example dataset and adding the documentation.
I managed to reproduce your example and just had to change two additional files: [embl.json](https://github.com/jhennies/AMST2/blob/main/amst2/cluster/embl.json) and [cluster.py] (https://github.com/jhennies/AMST2/blob/main/amst2/cluster/slurm.py) to be able to run amst2 on our local cluster.
What would be the next steps in order to test amst2 on another FIB sem dataset?

Thank you in advance and cheers,

Benjamin and Tatiana

**Comment by jhennies** [comment]
Ok, that's a great start :) 

In this case, you could follow the same instructions for your dataset starting with the pre-alignment
I'm assuming you have tif slices as individual files as well? 

The parameters that would require adjustment for the pre-alignment step are:

```
general:
  input_dirpath: /path/to/your/data/
  output_dirpath: /path/to/target/directory
  cores: 16  # Depends on your computing setup, for a cluster feel free to increase :) 
  batch_size: 8  # Breaks the task into smaller pieces. On the cluster, I normally use 32. Also, the z_step parameter below must not be larger than batch_size
  max_cores_per_task: 8  # Same value as batch size should work well

stack_to_ome_zarr:
  resolution: [z, y, x]   # Merely for visualization with a ome.zarr viewer, the pixel size is not used in the alignment method
  unit: micrometer

nsbs_alignment:
  z_step: 8  # Adjust the z-step if needed. I use 16 most of the time, but that can fail if the z-spacing of the slices is too large (> ~10 nm) and depending on the sample
```

The pre-alignment is the one that sometimes can be a bit tricky, that's where the final morphology of the sample in your dataset is determined and should yield a good result before continuing with the AMST step. 

For explanation:

The alignment here is performed in two main steps:

1. What I currently call a slice-by-slice (SBS) alignment (Fiji's "linear stack alignment with SIFT" is also an SBS alignment). Here I use crosscorrelation if the offset is large and refine with simple elastix. But importantly for the concept, each slice is aligned to the previous
2. A slice-by-slice alignment using composites (averages) of n (=z_step) consecutive slices (NSBS alignment). i.e. (assuming z_step=8) the average of slices 8 to 15 will be aligned to the average of slices 0 to 7, then average(16 to 23) to average(8 to 15), etc. This step determines the global morphology better than step 1. It is the replacement for the template matching alignment used in the original AMST method.

In case you want to use template matching instead of NSBS in step 2, we would currently have to set up a custom pipeline, but I would suggest, you test if this pipeline works for you. If it does and you have suitable markings in your platinum coating, you could use them to validate that the alignment properly reconstructed your data. If it worked well, the template will move little throughout the aligned dataset, similar to if it would have been used for alignment. 

Once the pre-alignment worked and gave a good result, the AMST step is pretty straight forward.

Cheers,
Julian
